font_family             JetBrainsMono Nerd Font
font_size               16.0
window_margin_width     5

open_url_with firefox
open_url_modifiers ctrl

enable_audio_bell no

foreground              #e0e0e0
background              #000000
cursor                  #b8d9ae
selection_background    #445c3d
selection_foreground    #e0e0e0
