music_directory     "~/music"
playlist_directory  "~/.config/mpd/playlists"
db_file             "~/.local/share/mpd/database"
state_file          "~/.local/state/mpd/state"
sticker_file        "~/.local/share/mpd/sticker.sql"
log_file            "~/.local/state/mpd/log"

bind_to_address     "127.0.0.1"
port                "6600"

auto_update         "yes"

audio_output {
    type            "pipewire"
    name            "PipeWire"
}
